<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="AccountServiceTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2023-01-25T05:41:31" hostname="DESKTOP-TTC8LD3" time="7.61">
  <properties/>
  <testcase name="start" classname="AccountServiceTest" time="7.61">
    <failure message="java.lang.AssertionError: Wrong answer in test #11&#10;&#10;POST /api/auth/signup should respond with status code 400 , responded: 200&#10;Response body:&#10;{&#10;  &quot;id&quot; : 1,&#10;  &quot;name&quot; : &quot;John&quot;,&#10;  &quot;lastname&quot; : &quot;Doe&quot;,&#10;  &quot;email&quot; : &quot;JohnDoe@acme.com&quot;&#10;}&#10;Request body:&#10;{&#10;  &quot;name&quot;: &quot;John&quot;,&#10;  &quot;lastname&quot;: &quot;Doe&quot;,&#10;  &quot;email&quot;: &quot;JohnDoe@acme.com&quot;,&#10;  &quot;password&quot;: &quot;PasswordForJanuary&quot;&#10;}&#10;Sending password from breached list" type="java.lang.AssertionError">java.lang.AssertionError: Wrong answer in test #11

POST /api/auth/signup should respond with status code 400 , responded: 200
Response body:
{
  &quot;id&quot; : 1,
  &quot;name&quot; : &quot;John&quot;,
  &quot;lastname&quot; : &quot;Doe&quot;,
  &quot;email&quot; : &quot;JohnDoe@acme.com&quot;
}
Request body:
{
  &quot;name&quot;: &quot;John&quot;,
  &quot;lastname&quot;: &quot;Doe&quot;,
  &quot;email&quot;: &quot;JohnDoe@acme.com&quot;,
  &quot;password&quot;: &quot;PasswordForJanuary&quot;
}
Sending password from breached list
	at org.junit.Assert.fail(Assert.java:89)
	at org.hyperskill.hstest.stage.StageTest.start(StageTest.java:203)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
</failure>
  </testcase>
  <system-out><![CDATA[?[1;31m
Start test 1?[0m
?[0;34m
?[0m?[0;34m  .   ____          _            __ _ _
?[0m?[0;34m /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
?[0m?[0;34m( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
?[0m?[0;34m \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
?[0m?[0;34m  '  |____| .__|_| |_|_| |_\__, | / / / /
?[0m?[0;34m =========|_|==============|___/=/_/_/_/
?[0m?[0;34m :: Spring Boot ::                (v2.7.6)
?[0m?[0;34m
?[0m?[0;34m2023-01-25 10:41:32.606  INFO 12348 --- [    Test worker] account.AccountServiceApplication        : Starting AccountServiceApplication using Java 17 on DESKTOP-TTC8LD3 with PID 12348 (started by zarak in C:\Users\zarak\IdeaProjects\Account Service\Account Service\task)
?[0m?[0;34m2023-01-25 10:41:32.609  INFO 12348 --- [    Test worker] account.AccountServiceApplication        : No active profile set, falling back to 1 default profile: "default"
?[0m?[0;34m2023-01-25 10:41:33.699  INFO 12348 --- [    Test worker] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
?[0m?[0;34m2023-01-25 10:41:33.799  INFO 12348 --- [    Test worker] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 83 ms. Found 1 JPA repository interfaces.
?[0m?[0;34m2023-01-25 10:41:34.653  INFO 12348 --- [    Test worker] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 28852 (http)
?[0m?[0;34m2023-01-25 10:41:34.669  INFO 12348 --- [    Test worker] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
?[0m?[0;34m2023-01-25 10:41:34.672  INFO 12348 --- [    Test worker] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.69]
?[0m?[0;34m2023-01-25 10:41:34.865  INFO 12348 --- [    Test worker] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
?[0m?[0;34m2023-01-25 10:41:34.866  INFO 12348 --- [    Test worker] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2188 ms
?[0m?[0;34m2023-01-25 10:41:35.118  INFO 12348 --- [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
?[0m?[0;34m2023-01-25 10:41:35.424  INFO 12348 --- [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
?[0m?[0;34m2023-01-25 10:41:35.438  INFO 12348 --- [    Test worker] o.s.b.a.h2.H2ConsoleAutoConfiguration    : H2 console available at '/h2-console'. Database available at 'jdbc:h2:file:../service_db'
?[0m?[0;34m2023-01-25 10:41:35.702  INFO 12348 --- [    Test worker] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
?[0m?[0;34m2023-01-25 10:41:35.787  INFO 12348 --- [    Test worker] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.14.Final
?[0m?[0;34m2023-01-25 10:41:36.083  INFO 12348 --- [    Test worker] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
?[0m?[0;34m2023-01-25 10:41:36.236  INFO 12348 --- [    Test worker] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
?[0m?[0;34mHibernate: create table app_user (id bigint not null, email varchar(255) not null, lastname varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id))
?[0m?[0;34mHibernate: create sequence hibernate_sequence start with 1 increment by 1
?[0m?[0;34m2023-01-25 10:41:37.021  INFO 12348 --- [    Test worker] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
?[0m?[0;34m2023-01-25 10:41:37.028  INFO 12348 --- [    Test worker] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
?[0m?[0;34m2023-01-25 10:41:37.416  WARN 12348 --- [    Test worker] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
?[0m?[0;34m2023-01-25 10:41:37.665  INFO 12348 --- [    Test worker] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@cce672c, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@496004e3, org.springframework.security.web.context.SecurityContextPersistenceFilter@51d76ad3, org.springframework.security.web.header.HeaderWriterFilter@4f836d9, org.springframework.security.web.authentication.logout.LogoutFilter@574134ba, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@52b7c1d9, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@1bca9b64, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@c7b100b, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@df34b01, org.springframework.security.web.session.SessionManagementFilter@3d8b9dee, org.springframework.security.web.access.ExceptionTranslationFilter@32675dd4, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@3fe21d0e]
?[0m?[0;34m2023-01-25 10:41:38.316  INFO 12348 --- [    Test worker] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 14 endpoint(s) beneath base path '/actuator'
?[0m?[0;34m2023-01-25 10:41:38.387  INFO 12348 --- [    Test worker] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 28852 (http) with context path ''
?[0m?[0;34m2023-01-25 10:41:38.418  INFO 12348 --- [    Test worker] account.AccountServiceApplication        : Started AccountServiceApplication in 6.227 seconds (JVM running for 7.221)
?[0;34m2023-01-25 10:41:38.728  INFO 12348 --- [io-28852-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
?[0m?[0;34m2023-01-25 10:41:38.728  INFO 12348 --- [io-28852-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
?[0m?[0;34m2023-01-25 10:41:38.730  INFO 12348 --- [io-28852-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
?[0m?[0;34m2023-01-25 10:41:38.867  WARN 12348 --- [io-28852-exec-1] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO): [Field error in object 'signupDTO' on field 'name': rejected value []; codes [NotEmpty.signupDTO.name,NotEmpty.name,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.name,name]; arguments []; default message [name]]; default message [must not be empty]] ]
?[0m?[1;31m
Start test 2?[0m
?[0;34m2023-01-25 10:41:38.916  WARN 12348 --- [io-28852-exec-3] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO) with 2 errors: [Field error in object 'signupDTO' on field 'name': rejected value [null]; codes [NotNull.signupDTO.name,NotNull.name,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.name,name]; arguments []; default message [name]]; default message [must not be null]] [Field error in object 'signupDTO' on field 'name': rejected value [null]; codes [NotEmpty.signupDTO.name,NotEmpty.name,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.name,name]; arguments []; default message [name]]; default message [must not be empty]] ]
?[1;31m
Start test 3?[0m
?[0;34m2023-01-25 10:41:38.929  WARN 12348 --- [io-28852-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO): [Field error in object 'signupDTO' on field 'lastname': rejected value []; codes [NotEmpty.signupDTO.lastname,NotEmpty.lastname,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.lastname,lastname]; arguments []; default message [lastname]]; default message [must not be empty]] ]
?[1;31m
Start test 4?[0m
?[0;34m2023-01-25 10:41:38.957  WARN 12348 --- [io-28852-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO) with 2 errors: [Field error in object 'signupDTO' on field 'lastname': rejected value [null]; codes [NotNull.signupDTO.lastname,NotNull.lastname,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.lastname,lastname]; arguments []; default message [lastname]]; default message [must not be null]] [Field error in object 'signupDTO' on field 'lastname': rejected value [null]; codes [NotEmpty.signupDTO.lastname,NotEmpty.lastname,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.lastname,lastname]; arguments []; default message [lastname]]; default message [must not be empty]] ]
?[1;31m
Start test 5?[0m
?[0;34m2023-01-25 10:41:38.971  WARN 12348 --- [io-28852-exec-6] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO) with 2 errors: [Field error in object 'signupDTO' on field 'email': rejected value []; codes [Email.signupDTO.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@3a9ad8e7,.+@acme\.com$]; default message [must be a well-formed email address]] [Field error in object 'signupDTO' on field 'email': rejected value []; codes [NotEmpty.signupDTO.email,NotEmpty.email,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.email,email]; arguments []; default message [email]]; default message [must not be empty]] ]
?[1;31m
Start test 6?[0m
?[0;34m2023-01-25 10:41:38.987  WARN 12348 --- [o-28852-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO) with 2 errors: [Field error in object 'signupDTO' on field 'email': rejected value [null]; codes [NotEmpty.signupDTO.email,NotEmpty.email,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.email,email]; arguments []; default message [email]]; default message [must not be empty]] [Field error in object 'signupDTO' on field 'email': rejected value [null]; codes [NotNull.signupDTO.email,NotNull.email,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.email,email]; arguments []; default message [email]]; default message [must not be null]] ]
?[1;31m
Start test 7?[0m
?[0;34m2023-01-25 10:41:39.003  WARN 12348 --- [io-28852-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO): [Field error in object 'signupDTO' on field 'password': rejected value []; codes [NotEmpty.signupDTO.password,NotEmpty.password,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.password,password]; arguments []; default message [password]]; default message [must not be empty]] ]
?[1;31m
Start test 8?[0m
?[0;34m2023-01-25 10:41:39.015  WARN 12348 --- [io-28852-exec-8] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO) with 2 errors: [Field error in object 'signupDTO' on field 'password': rejected value [null]; codes [NotNull.signupDTO.password,NotNull.password,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.password,password]; arguments []; default message [password]]; default message [must not be null]] [Field error in object 'signupDTO' on field 'password': rejected value [null]; codes [NotEmpty.signupDTO.password,NotEmpty.password,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.password,password]; arguments []; default message [password]]; default message [must not be empty]] ]
?[1;31m
Start test 9?[0m
?[0;34m2023-01-25 10:41:39.029  WARN 12348 --- [io-28852-exec-4] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO): [Field error in object 'signupDTO' on field 'email': rejected value [johndoeacme.com]; codes [Email.signupDTO.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@3a9ad8e7,.+@acme\.com$]; default message [must be a well-formed email address]] ]
?[1;31m
Start test 10?[0m
?[0;34m2023-01-25 10:41:39.039  WARN 12348 --- [io-28852-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> account.auth.AuthController.signup(account.DTOs.SignupDTO): [Field error in object 'signupDTO' on field 'email': rejected value [johndoe@google.com]; codes [Email.signupDTO.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signupDTO.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@3a9ad8e7,.+@acme\.com$]; default message [must be a well-formed email address]] ]
?[1;31m
Start test 11?[0m
?[0m?[0;34mHibernate: select appuser0_.id as id1_0_, appuser0_.email as email2_0_, appuser0_.lastname as lastname3_0_, appuser0_.name as name4_0_, appuser0_.password as password5_0_ from app_user appuser0_ where upper(appuser0_.email)=upper(?)
?[0m?[0;34mHibernate: call next value for hibernate_sequence
?[0m?[0;34mHibernate: insert into app_user (email, lastname, name, password, id) values (?, ?, ?, ?, ?)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
